all:
  vars:
    # SSH 用户
    ansible_user: zze
    # SSH 密码
    ansible_ssh_pass: root1234
    # sudo 提权密码
    ansible_sudo_pass: root1234
    # Redis 编译好的二进制文件目录
    bin_dir: /opt/redis_bin
    # 安装目录
    install_dir: /opt/apps
    # 主实例端口
    master_port: 6379
    # 从实例端口
    slave_port: 6380
    # Redis 密码
    password: 123
    # 集群副本数
    cluster_replicas: 1
  hosts:
    10.0.1.111:
    10.0.1.112:
    10.0.1.113: